version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tarek
      - MONGO_INITDB_ROOT_PASSWORD=tarekpassword
    volumes:
      - mongo-db:/data/db

volumes:
  - mongo-db:
